Update release.yml

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -20,14 +20,25 @@ jobs:
         run: |
           git submodule sync --recursive
           git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
+      - name: Get tag
+        shell: bash
+        id: mod
+        run: |
+          tag="${{ github.ref_name }}"
+          echo "out=untitled-ibus-handwriting-${tag:1}" >> $GITHUB_OUTPUT
       - name: Create archive
         shell: bash
         run: |
-          rm -rf .git/
           cd hanzi_lookup || exit
           cargo vendor || (ls hanzi_lookup && exit)
           cd .. || exit
-          tar cfJ untitled-ibus-handwriting.tar.xz . || echo "Might have failed"
+          
+          rm -rf .git/
+          mkdir "${{ steps.mod.outputs.out }}" || exit
+          mv * ${{ steps.mod.outputs.out }}/ || echo "Errors in move"
+          mv .* "${{ steps.mod.outputs.out }}" || echo "Errors in move"
+
+          tar cfJ ${{ steps.mod.outputs.out }}.tar.xz ${{ steps.mod.outputs.out }} || echo "Might have failed"
       - name: Create Release
         uses: softprops/action-gh-release@v2
         with:
@@ -36,5 +47,5 @@ jobs:
             More on what is done this month can be found on the latest newsletter entry: https://madladsquad.com/#monthly-newsletter
           draft: false
           prerelease: false
-          files: untitled-ibus-handwriting.tar.xz
+          files: ${{ steps.mod.outputs.out }}.tar.xz
           generate_release_notes: false
